---
name: Delivery

on:
  push:
    branches:
      - main

env:
  DOCKER_IMAGE_DIRECTORIES: ("linter")

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Publish the images that have changed
        run: |
          FILES=$(git diff --name-only --diff-filter=ACMRT ${{ github.event.before }} ${GITHUB_SHA})
          readarray -t FILES_ARRAY <<< "$FILES"
          IFS='/'
          DOCKER_IMAGES_PUSHED=()

          for FILENAME in "${FILES_ARRAY[@]}"; do
            read -a PATH_FILE <<< "$FILENAME"
            if [[ ! "${DOCKER_IMAGE_DIRECTORIES[*]}" =~ "${PATH_FILE[0]}" ]]; then
              continue
            fi
            if [[ " ${DOCKER_IMAGES_PUSHED[*]} " =~ " ${PATH_FILE[0]} " ]]; then
              continue
            fi

            DOCKER_IMAGE_NAME="${{ secrets.DOCKERHUB_USERNAME }}/${PATH_FILE[0]}"
            docker build "${PATH_FILE[0]}" -t "${DOCKER_IMAGE_NAME}"
            docker push "${DOCKER_IMAGE_NAME}"
            DOCKER_IMAGES_PUSHED+=("${PATH_FILE[0]}")
          done
